ci/cd:
  - '.github/**'
  - '! .github/PULL_REQUEST_TEMPLATE.md'
  - '! .github/labeler.yml'
  - '! .github/workflows/pr-labeler.yml'

tables:
  - 'prisma/**'

crud:
  - 'src/**'

tests:
  - 'test/**'

gitWorkflow:
  - '.github/PULL_REQUEST_TEMPLATE.md'
  - '.github/labeler.yml'
  - '.github/workflows/pr-labeler.yml'

Documentation:
  - '**/*.md'
