ci/cd:
- changed-files:
  - any-glob-to-any-files: .github/**
  - all-globs-to-all-files: ['!.github/PULL_REQUEST_TEMPLATE.md', '!.github/labeler.yml', '!.github/workflows/pr-labeler.yml']

tables:
- changed-files:
  - any-glob-to-any-files: prisma/**

crud:
- changed-files:
  - any-glob-to-any-files: src/**

tests:
- changed-files:
  - any-glob-to-any-files: test/**

gitWorkflow:
- changed-files:
  - all-globs-to-all-files: ['.github/PULL_REQUEST_TEMPLATE.md', '.github/labeler.yml', '.github/workflows/pr-labeler.yml']

Documentation:
- changed-files:
  - any-glob-to-any-files: '**/*.md'