services:
  postgres:
    container_name: postgres
    image: postgres:latest
    # env_file:
    #   - .env  # Charge toutes les variables du fichier .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

  backend:
    container_name: nestappcompose
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    # env_file:
    #   - .env  # Charge aussi les variables pour pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "8080:80"  # Mappe le port 80 de pgAdmin au port 8080 de l'hôte
    restart: always