name: Build and publish Docker image
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        - name: Build the Docker image
          run: |
            IMAGE_TAG=${GITHUB_SHA::7}
            docker build -t ${{ secrets.DOCKER_USERNAME }}/youlinkbackend:$IMAGE_TAG .
            docker build -t ${{ secrets.DOCKER_USERNAME }}/youlinkbackend:latest .
        - name: Push image to Docker Hub
          run: |
            IMAGE_TAG=${GITHUB_SHA::7}
            docker push ${{ secrets.DOCKER_USERNAME }}/youlinkbackend:$IMAGE_TAG          
            docker push ${{ secrets.DOCKER_USERNAME }}/youlinkbackend:latest
