# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Output node version
      run: node --version
    - name: Install dependancies
      run: npm ci
    - name: Build project
      run: npm run build --if-present
    - name: Build with success
      run: echo "Build with success !"
    - name: Build with logs
      run: |
        mkdir ${{ runner.temp }}/build_logs
        echo "Logs from building" > ${{ runner.temp }}/build_logs/build.logs
        exit 1
    - name: Upload logs on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: Build failure logs
        path: ${{ runner.temp }}/build_logs
    - name: Run test
      run: npm test --if-present

  debug:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo "Failed to build"
