name: Deploy to Railway

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install Railway CLI
              run: npm install -g @railway/cli

            - name: Login to Railway
              run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

            - name: Deploy to Railway
              run: railway up --service Links-to-Experts-Back
              env: 
                RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}