name: Deploy to Railway

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install Railway CLI
              run: npm install -g railway

            - name: Deploy to Railway
              run: railway up --service youlink-api
              env: 
                RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}